export const projects = [
  {
    id: 18,
    name: "test 1",
    name_cn: null,
    leader_id: 6,
    created_by: 4,
    images:
      "images/1690452427_test.svg,images/1690506179_login.png,images/1690529986_setup-lightshot.exe",
    logo: "images/1690448313_lock.png",
    desc: null,
    status: 2,
    estimate_time: 0,
    due_date: null,
    start_date: null,
    created_at: "2023-07-27T04:20:52.000000Z",
    updated_at: "2023-08-05T04:17:22.000000Z",
    tasks: [
      {
        id: 52,
        task_name: "test 11",
        task_desc: null,
        priority_id: 1,
        status_id: 1,
        project_id: 18,
        department_id: 0,
        parent_id: 0,
        author_id: 4,
        tracker_id: 1,
        start_date: null,
        due_date: "2023-08-04 00:00:00",
        estimate_time: "0.0",
        logged_time: 0,
        done_ratio: 0,
        attack_file: "",
        is_active: 0,
        done_at: null,
        created_at: "2023-08-03T03:04:12.000000Z",
        updated_at: "2023-08-05T04:07:08.000000Z",
        sub_task: [],
        task_members: [
          {
            id: 8,
            name: "wuchaos",
            color: null,
            pivot: {
              task_id: 52,
              user_id: 8,
            },
          },
        ],
        status: {
          id: 1,
          color: "#cae2d5",
        },
      },
    ],
    members: [
      {
        id: 6,
        name: "zhaofei",
        color: null,
        pivot: {
          project_id: 18,
          user_id: 6,
        },
      },
      {
        id: 5,
        name: "Nguyễn Đình Vượng",
        color: null,
        pivot: {
          project_id: 18,
          user_id: 5,
        },
      },
      {
        id: 8,
        name: "wuchaos",
        color: null,
        pivot: {
          project_id: 18,
          user_id: 8,
        },
      },
      {
        id: 4,
        name: "Super Admin",
        color: "#F24D16",
        pivot: {
          project_id: 18,
          user_id: 4,
        },
      },
    ],
  },
  {
    id: 20,
    name: "test 2",
    name_cn: null,
    leader_id: 5,
    created_by: 4,
    images: "",
    logo: null,
    desc: null,
    status: 1,
    estimate_time: 0,
    due_date: null,
    start_date: null,
    created_at: "2023-07-28T07:55:01.000000Z",
    updated_at: "2023-07-28T07:55:09.000000Z",
    tasks: [
      {
        id: 54,
        task_name: "test 21",
        task_desc: null,
        priority_id: 1,
        status_id: 1,
        project_id: 20,
        department_id: 0,
        parent_id: 0,
        author_id: 4,
        tracker_id: 1,
        start_date: null,
        due_date: "2023-08-25 00:00:00",
        estimate_time: "0.0",
        logged_time: 0,
        done_ratio: 0,
        attack_file: "",
        is_active: 0,
        done_at: null,
        created_at: "2023-08-03T03:13:42.000000Z",
        updated_at: "2023-08-05T03:41:18.000000Z",
        sub_task: [
          {
            id: 69,
            task_name: "test 211",
            task_desc: null,
            priority_id: 1,
            status_id: 1,
            project_id: 20,
            department_id: 0,
            parent_id: 54,
            author_id: 4,
            tracker_id: 0,
            start_date: null,
            due_date: "2023-08-07 00:00:00",
            estimate_time: "0.0",
            logged_time: 0,
            done_ratio: 0,
            attack_file: "",
            is_active: 0,
            done_at: null,
            created_at: "2023-08-05T04:11:50.000000Z",
            updated_at: "2023-08-05T09:40:32.000000Z",
            sub_task: [
              {
                id: 70,
                task_name: "test 212",
                task_desc: null,
                priority_id: 1,
                status_id: 1,
                project_id: 20,
                department_id: 0,
                parent_id: 69,
                author_id: 4,
                tracker_id: 0,
                start_date: null,
                due_date: "2023-08-22 00:00:00",
                estimate_time: "0.0",
                logged_time: 0,
                done_ratio: 0,
                attack_file: "",
                is_active: 0,
                done_at: null,
                created_at: "2023-08-05T04:12:24.000000Z",
                updated_at: "2023-08-05T09:59:16.000000Z",
                sub_task: [],
                task_members: [
                  {
                    id: 5,
                    name: "Nguyễn Đình Vượng",
                    color: null,
                    pivot: {
                      task_id: 70,
                      user_id: 5,
                    },
                  },
                ],
                status: {
                  id: 1,
                  color: "#cae2d5",
                },
              },
              {
                id: 73,
                task_name: "test 213",
                task_desc: null,
                priority_id: 1,
                status_id: 1,
                project_id: 20,
                department_id: 0,
                parent_id: 69,
                author_id: 4,
                tracker_id: 0,
                start_date: null,
                due_date: "2023-08-25 00:00:00",
                estimate_time: "0.0",
                logged_time: 0,
                done_ratio: 0,
                attack_file: "",
                is_active: 0,
                done_at: null,
                created_at: "2023-08-05T04:14:49.000000Z",
                updated_at: "2023-08-05T10:17:07.000000Z",
                sub_task: [
                  {
                    id: 74,
                    task_name: "test 2131",
                    task_desc: null,
                    priority_id: 1,
                    status_id: 1,
                    project_id: 20,
                    department_id: 0,
                    parent_id: 73,
                    author_id: 4,
                    tracker_id: 0,
                    start_date: null,
                    due_date: "2023-08-10 00:00:00",
                    estimate_time: "0.0",
                    logged_time: 0,
                    done_ratio: 0,
                    attack_file: "",
                    is_active: 0,
                    done_at: null,
                    created_at: "2023-08-05T04:46:45.000000Z",
                    updated_at: "2023-08-05T10:11:42.000000Z",
                    sub_task: [],
                    task_members: [
                      {
                        id: 5,
                        name: "Nguyễn Đình Vượng",
                        color: null,
                        pivot: {
                          task_id: 74,
                          user_id: 5,
                        },
                      },
                    ],
                    status: {
                      id: 1,
                      color: "#cae2d5",
                    },
                  },
                ],
                task_members: [
                  {
                    id: 5,
                    name: "Nguyễn Đình Vượng",
                    color: null,
                    pivot: {
                      task_id: 73,
                      user_id: 5,
                    },
                  },
                ],
                status: {
                  id: 1,
                  color: "#cae2d5",
                },
              },
            ],
            task_members: [
              {
                id: 5,
                name: "Nguyễn Đình Vượng",
                color: null,
                pivot: {
                  task_id: 69,
                  user_id: 5,
                },
              },
            ],
            status: {
              id: 1,
              color: "#cae2d5",
            },
          },
        ],
        task_members: [
          {
            id: 5,
            name: "Nguyễn Đình Vượng",
            color: null,
            pivot: {
              task_id: 54,
              user_id: 5,
            },
          },
        ],
        status: {
          id: 1,
          color: "#cae2d5",
        },
      },
      {
        id: 77,
        task_name: "test 22",
        task_desc: "<p>ooooo</p>",
        priority_id: 1,
        status_id: 1,
        project_id: 20,
        department_id: 0,
        parent_id: 0,
        author_id: 4,
        tracker_id: 0,
        start_date: null,
        due_date: "2023-08-23 00:00:00",
        estimate_time: "0.0",
        logged_time: 0,
        done_ratio: 0,
        attack_file: "",
        is_active: 0,
        done_at: null,
        created_at: "2023-08-05T09:09:42.000000Z",
        updated_at: "2023-08-05T09:09:42.000000Z",
        sub_task: [
          {
            id: 75,
            task_name: "test 221",
            task_desc: null,
            priority_id: 1,
            status_id: 1,
            project_id: 20,
            department_id: 0,
            parent_id: 77,
            author_id: 4,
            tracker_id: 0,
            start_date: null,
            due_date: "2023-08-23 00:00:00",
            estimate_time: "0.0",
            logged_time: 0,
            done_ratio: 0,
            attack_file: "",
            is_active: 0,
            done_at: null,
            created_at: "2023-08-05T08:49:54.000000Z",
            updated_at: "2023-08-05T09:47:08.000000Z",
            sub_task: [],
            task_members: [
              {
                id: 5,
                name: "Nguyễn Đình Vượng",
                color: null,
                pivot: {
                  task_id: 75,
                  user_id: 5,
                },
              },
            ],
            status: {
              id: 1,
              color: "#cae2d5",
            },
          },
          {
            id: 76,
            task_name: "test 223",
            task_desc: null,
            priority_id: 3,
            status_id: 3,
            project_id: 20,
            department_id: 0,
            parent_id: 77,
            author_id: 4,
            tracker_id: 0,
            start_date: null,
            due_date: "2023-08-26 00:00:00",
            estimate_time: "0.0",
            logged_time: 0,
            done_ratio: 100,
            attack_file: "",
            is_active: 0,
            done_at: "2023-08-05 17:11:55",
            created_at: "2023-08-05T09:00:20.000000Z",
            updated_at: "2023-08-05T10:11:55.000000Z",
            sub_task: [],
            task_members: [
              {
                id: 5,
                name: "Nguyễn Đình Vượng",
                color: null,
                pivot: {
                  task_id: 76,
                  user_id: 5,
                },
              },
            ],
            status: {
              id: 3,
              color: "#00f010",
            },
          },
        ],
        task_members: [
          {
            id: 5,
            name: "Nguyễn Đình Vượng",
            color: null,
            pivot: {
              task_id: 77,
              user_id: 5,
            },
          },
        ],
        status: {
          id: 1,
          color: "#cae2d5",
        },
      },
    ],
    members: [
      {
        id: 5,
        name: "Nguyễn Đình Vượng",
        color: null,
        pivot: {
          project_id: 20,
          user_id: 5,
        },
      },
    ],
  },
  {
    id: 19,
    name: "test 3",
    name_cn: null,
    leader_id: 5,
    created_by: 4,
    images: "images/1690452656_lock.png,images/1690452656_user.png",
    logo: "images/1690452650_Layer881.png",
    desc: "<p>o</p>",
    status: 1,
    estimate_time: 0,
    due_date: null,
    start_date: null,
    created_at: "2023-07-27T10:10:59.000000Z",
    updated_at: "2023-07-27T10:10:59.000000Z",
    tasks: [
      {
        id: 44,
        task_name: "test 31",
        task_desc: null,
        priority_id: 2,
        status_id: 6,
        project_id: 19,
        department_id: 0,
        parent_id: 0,
        author_id: 4,
        tracker_id: 1,
        start_date: null,
        due_date: "2023-07-28 00:00:00",
        estimate_time: "0.0",
        logged_time: 0,
        done_ratio: 100,
        attack_file: "",
        is_active: 0,
        done_at: "2023-08-04 08:36:31",
        created_at: "2023-07-27T10:27:51.000000Z",
        updated_at: "2023-08-04T01:36:31.000000Z",
        sub_task: [],
        task_members: [
          {
            id: 5,
            name: "Nguyễn Đình Vượng",
            color: null,
            pivot: {
              task_id: 44,
              user_id: 5,
            },
          },
        ],
        status: {
          id: 6,
          color: "#0a0000",
        },
      },
      {
        id: 50,
        task_name: "test 32",
        task_desc: null,
        priority_id: 2,
        status_id: 3,
        project_id: 19,
        department_id: 0,
        parent_id: 0,
        author_id: 4,
        tracker_id: 1,
        start_date: null,
        due_date: "2023-07-11 00:00:00",
        estimate_time: "0.0",
        logged_time: 0,
        done_ratio: 100,
        attack_file: "",
        is_active: 0,
        done_at: "2023-08-01 12:32:59",
        created_at: "2023-07-28T09:30:06.000000Z",
        updated_at: "2023-08-01T05:32:59.000000Z",
        sub_task: [],
        task_members: [
          {
            id: 5,
            name: "Nguyễn Đình Vượng",
            color: null,
            pivot: {
              task_id: 50,
              user_id: 5,
            },
          },
        ],
        status: {
          id: 3,
          color: "#00f010",
        },
      },
    ],
    members: [
      {
        id: 5,
        name: "Nguyễn Đình Vượng",
        color: null,
        pivot: {
          project_id: 19,
          user_id: 5,
        },
      },
    ],
  },
];
